name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          yarn run clean
          yarn workspaces run build
      - name: Quality
        run: |
          yarn run lint
      - name: Publish Web Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: |
            modules/*/dist/web/*
            !modules/*/dist/web/*.txt
      - name: Publish Documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            modules/*/docs/out/*
      - name: Configure Publish
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@openhps.org'
      - name: Bump version development
        if: github.ref == 'refs/heads/dev'
        run: |
          yarn workspaces run bump:development
      - name: Bump version release
        if: github.ref == 'refs/heads/master'
        run: |
          yarn workspaces run bump:release
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Publish to GitHub
        if: success()
        run: |
          git push